### ISSUE TITLE
Error: <ConnectionTerminated error_code:ErrorCodes.NO_ERROR, last_stream_id:19999, additional_data:None>

### ISSUE THREAD

**Issue by rishabh1815769** [qdrant/qdrant#2371] opened 2023-08-02 06:41 UTC
```
Error: <ConnectionTerminated error_code:ErrorCodes.NO_ERROR, last_stream_id:19999, additional_data:None>
```

## Current Behavior
```
Error: <ConnectionTerminated error_code:ErrorCodes.NO_ERROR, last_stream_id:19999, additional_data:None>
```

## Steps to Reproduce
```python
with open('qdrant_file_embeddings.json', 'r') as file:
    df = json.load(file)
print("Json File Loaded!")

for i in range(len(df)):
    data_without_embeddings = df[i].copy()
    data_without_embeddings.pop('hotel_description_embeddings', None)
    
    try:
        client.upsert(
            collection_name="hotel_default_location_embeddings",
            points=[
                models.PointStruct(
                    id=int(df[i]['h_key']),
                    payload=data_without_embeddings,
                    vector=df[i]['hotel_description_embeddings'],
                ),
            ]
        )
    except Exception as e:
        print(f"Failed to upsert record with id: {int(df[i]['h_key'])}, index: {i}. Error: {str(e)}")
        continue
print("Records Inserted!")
```

I am reading a list of dictionaries and upserting the records using the code above. But after every 10000 records one record fails to upsert with the error: Error: <ConnectionTerminated error_code:ErrorCodes.NO_ERROR, last_stream_id:19999, additional_data:None>.
Import thing to note here is it fails **Exactly** after 10000 records. Do we have any connection resets or any limitations on HTTP protocol. I am not using gRPC as of now.

![image](https://github.com/qdrant/qdrant/assets/58872311/d6413904-0886-4439-a007-d5dc19081180)

**Comment by generall** [comment] 2023-08-02 08:16
Hi @rishabh1815769, there is no limitation in HTTP except for the max size of the request (32Mb).
Could you please provide more information regarding the environment where you are runnning qdrant?

Is it cloud/self-hosted? Is there any proxies in between?

Also it is hard to reproduce your snippet without actual data, could you please provide an example which can be actually executed to reproduce the problem? It might use fake data as long as the error is still observable.

**Comment by agourlay** [comment] 2023-08-24 12:40
This seems to be a client issue https://github.com/encode/httpx/discussions/2112

Many people recommend deactivating http2 which we have done in https://github.com/qdrant/qdrant-client/pull/258

Maybe you could try the master branch of the Python client.

**Comment by generall** [comment] 2023-12-25 17:24
Assuming the problem was fixed on client side, please feel free to re-open if it still reproduces

**Closed by generall** 2023-12-25 17:24 UTC
Labels: bug
