### ISSUE TITLE
Add merge option to set payload API

### ISSUE THREAD

**Issue by keotic** [qdrant/qdrant#2327] opened 2023-07-25 19:45 UTC
**Is your feature request related to a problem? Please describe.**
Currently the set_payload API probably ignores or overrides existing payloads of existing points.
An option to merge new payloads with existing payload of a point will be useful.

**Describe the solution you'd like**
An option to merge new payloads with existing ones, with a payload key (probably indexed) stating uniqueness.
The merge should be thread safe, i.e: assume many clients try to merge new payloads of a point and 
handle race conditions via the uniqueness key.

For example:
1. Assume existing point in DB:
```
{
   "id" : 1,
   "payload" : { x : 1, y : 2 }
}
```

2. Set payload with merge
```
{
   "id" : 1,
   "payload" : { z : 3 }
}
```

3. The resulting point on DB should be:
```
{
   "id" : 1,
   "payload" : { x : 1, y : 2, z: 3 }
}

```

**Describe alternatives you've considered**

**Additional context**
https://qdrant.tech/documentation/concepts/payload/#set-payload

**Comment by nkbelov** [comment] 2023-08-04 19:17
This might be hard or even nigh impossible to cleanly implement in a sufficiently generic way because there are many possibilities to merge conflicting fields, and the database probably shouldn't assume which one is correct.

Consider merging `{ x: 1, y: { a: 0 } }` with `{ x: 1, y: { b: 1, c: 2 } }` : should the result be `{x: 1, y: { a: 0 }}`, `{x: 1, y: { b: 1, c: 2 } }` or `{ x: 1, y: { a: 0, b: 1, c: 2 } }`?

Depending on the use case, you may want any of the three options. The problem is exacerbated when you have conflicting fields of different types: how would you merge `{x: ["a", "b", "c"]}` with `{x: { a: 0, b: 1, c: 2 }}`?

There are potential solutions, but each of them have major downsides:

1. Bail on any conflict — this will avoid the problem altogether, but is very limiting and won't be idempotent;
2. Choose a single policy, like last-write-wins (although it's also a major question what's considered "last" in a concurrent environment) — will also be unproblematic from the DB's side but won't allow the 3rd option in my first example;
3. Try to merge as deeply as possible — concat all arrays and union all dictionaries/objects, but it's still unclear what to do with heterogeneous fields,
4. Make the client specify a policy for each field — would be the most flexible, but requires the client to be very aware of the structure of the payload prior to making the request.

The first three options effectively render the feature unusable in the cases where the DB's choice is undesirable, whereas the fourth version might end up more problematic to use than simply fetching the payload and updating it on the client with the exact semantics that you want.

**Comment by keotic** [comment] 2023-08-04 21:41
Thanks for the detailed reply. Would option 4 which defines a unique key for the merge ( probably indexed key ) is problematic?
Fetching the payload on every update / upsert and manipulating it on the client may consume a lot of resources (networking + cpu).

Consider the following scenario:
Insert 500M points with payload of 1KB to an existing collection (thats 500GB of payloads)
Without a backend merge for we need to try and retrieve each point and its payload before the actual insert, meaning we have an extra 500GB fetched from the backend to the client if all the points already exist.
Than if the fetched payloads are not intersected with the inserted payloads, the client side merge will create 2KB payload to write back to the DB.
All in all its an extra 1T of data transfer which is problematic in high scale production systems.

**Comment by nkbelov** [comment] 2023-08-04 22:09
Full disclosure: I'm not affiliated to qdrant, just responding as a database enthusiast. 

I'm not sure what you mean by "unique key for the merge", do you mean a path into the payload like `payload.someField.someInnerField` into which the merge should be performed?

I understand the concern with the transfer volume, but if you want to avoid it, the database has to have a clear understanding of how to merge *precisely your* data, which is not a general use case. There are some clever data types (CRDTs) which are specifically made to allow arbitrary merges, but qdrant is not exactly a CRDT database, at least at this moment.

It is, to my understanding, generic over the payload of the points, which means that any point in a given collection can potentially have arbitrarily structured data, which makes it even harder to offer a concise API for merging: not only would you  have to provide a merger mechanism for a certain schema, you'd also have to ensure that it applies to *each* data point you're about to merge into. 

If you have *n* arbitrarily heterogeneous payloads, this effectively means that you still have to specify an *O(n)* number of merging strategies, which doesn't reduce the data volume as much.

**Comment by keotic** [comment] 2023-08-04 22:20
Yes, by "unique key for the merge" I mean a key provided by the user on the which the merge mechanism will make a resolution about merge / insert , i.e: the fields under the given key must be unique.
Would it solve the problems you mentioned?

Yes Qdrant is not a CRDT yet, I am raising these issues in order to understand if to treat it as a DB or an Index that should b be used over a DB in order to be considered for production scales.

**Comment by nkbelov** [comment] 2023-08-04 22:31
>  the fields under the given key must be unique

Even if they are unique, they still may be heterogeneous: suppose I have a DB of only two points, one of which stores a `{x: "hello"}` payload; the other stores an `{x: ["world"]}` payload. These are unique in the sense that they won't compare under the typical equality notion (one is an object/dictionary; the other is an array), but it's impossible to say definitively how these should be merged.

How would you expect a merger of those to reconcile?

**Comment by keotic** [comment] 2023-08-04 22:41
I would expect it to be
{x: ["hello", ["world"]]}

But it doesn't really matter, all I ask from the DB is a guarantee of uniqueness of the values under the merge key.
Since the user applies the key, it should be aware of inconsistencies.
Or we can simplify and force the same schema on merge keys values, raising an error on merge conflicts

**Comment by generall** [comment] 2023-12-10 16:55
> Currently the set_payload API probably ignores or overrides existing payloads of existing points.


That's actually not the case. `set_payload` is only overwriting specified fields.

There is another method to overwrite payload: https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/overwrite_payload

**Closed by generall** 2023-12-10 16:55 UTC
Labels: enhancement
