### ISSUE TITLE
qdrant does not update multiple named vectors on the same point

### ISSUE THREAD

**Issue by milosgajdos** [qdrant/qdrant#3376] opened 2024-01-11 06:12 UTC
I might be missing something here with regard to how to update named vectors on the same point but when using the [Go client](https://github.com/qdrant/go-client), it would appear that only one of them gets updated. What gives?

## Steps to Reproduce

1. Create a collection with 2 named vectors
2. Upsert a point
3. Update named vectors on the same point
4. List the named vectors on the upserted point

Here is the Go code that can reproduce the issue:
<details><summary>Go code</summary>

```Go
package main

import (
	"context"
	"log"

	"github.com/google/uuid"
	pb "github.com/qdrant/go-client/qdrant"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

var (
	defaultDistance = pb.Distance_Dot
)

func main() {
	conn, err := grpc.DialContext(context.Background(),
		"localhost:6334",
		grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatalf("Failed to connect: %v", err)
	}
	defer conn.Close()

	col := pb.NewCollectionsClient(conn)

	uid := uuid.New().String()
	ctx := context.Background()

	_, err = col.Create(ctx, &pb.CreateCollection{
		CollectionName: uid,
		VectorsConfig: &pb.VectorsConfig{
			Config: &pb.VectorsConfig_ParamsMap{
				ParamsMap: &pb.VectorParamsMap{
					Map: map[string]*pb.VectorParams{
						"": {
							Size:     4,
							Distance: defaultDistance,
						},
						"2D": {
							Size:     2,
							Distance: defaultDistance,
						},
						"3D": {
							Size:     3,
							Distance: defaultDistance,
						},
					},
				},
			},
		},
	})
	if err != nil {
		log.Fatalf("collection create failed: %v", err)
	}

	log.Printf("created collection: %s", uid)

	pts := pb.NewPointsClient(conn)

	pointUID := uuid.NewString()
	upsertPoints := []*pb.PointStruct{
		{
			Id: &pb.PointId{
				PointIdOptions: &pb.PointId_Uuid{
					Uuid: pointUID,
				},
			},
			Vectors: &pb.Vectors{
				VectorsOptions: &pb.Vectors_Vector{
					Vector: &pb.Vector{
						Data: []float32{1.0, 2.0, 3.0, 4.0},
					},
				},
			},
		},
	}

	waitUpsert := true
	if _, err := pts.Upsert(ctx, &pb.UpsertPoints{
		CollectionName: uid,
		Wait:           &waitUpsert,
		Points:         upsertPoints,
	}); err != nil {
		log.Fatalf("failed upserting: %v", err)
	}

	log.Printf("upserted point: %v", pointUID)

	vectors := []*pb.PointVectors{
		{
			Id: &pb.PointId{
				PointIdOptions: &pb.PointId_Uuid{
					Uuid: pointUID,
				},
			},
			Vectors: &pb.Vectors{
				VectorsOptions: &pb.Vectors_Vectors{
					Vectors: &pb.NamedVectors{
						Vectors: map[string]*pb.Vector{
							"2D": {
								Data: []float32{1.1, 2.2},
							},
						},
					},
				},
			},
		},
		{
			Id: &pb.PointId{
				PointIdOptions: &pb.PointId_Uuid{
					Uuid: pointUID,
				},
			},
			Vectors: &pb.Vectors{
				VectorsOptions: &pb.Vectors_Vectors{
					Vectors: &pb.NamedVectors{
						Vectors: map[string]*pb.Vector{
							"3D": {
								Data: []float32{1.1, 2.2, 3.3},
							},
						},
					},
				},
			},
		},
	}

	for _, v := range vectors {
		for dim, vec := range v.Vectors.GetVectors().GetVectors() {
			log.Printf("updating point: %#v named vector: %v, data: %v\n", v.Id.GetUuid(), dim, vec.Data)
		}
	}

	if _, err := pts.UpdateVectors(ctx, &pb.UpdatePointVectors{
		CollectionName: uid,
		Wait:           &waitUpsert,
		Points:         vectors,
	}); err != nil {
		log.Fatalf("failed updating vectors: %v", err)
	}

	//////// SCROLL ALL POINTS AND COLLECT NAMED VECTORS ///////
	req := &pb.ScrollPoints{
		CollectionName: uid,
		WithVectors: &pb.WithVectorsSelector{
			SelectorOptions: &pb.WithVectorsSelector_Enable{
				Enable: true,
			},
		},
		WithPayload: &pb.WithPayloadSelector{
			SelectorOptions: &pb.WithPayloadSelector_Enable{
				Enable: true,
			},
		},
	}

	resp, err := pts.Scroll(ctx, req)
	if err != nil {
		log.Fatalf("failed scrolling collection: %v", uid)
	}

	points := resp.GetResult()

	points2D := make([][]float32, 0, len(points))
	points3D := make([][]float32, 0, len(points))

	for _, p := range points {
		vecs := p.GetVectors().GetVectors()
		for _, dim := range []string{"2D", "3D"} {
			if vecs != nil {
				if vecs.Vectors[dim] != nil {
					vecData := vecs.Vectors[dim].Data
					vals := make([]float32, 0, len(vecData))
					vals = append(vals, vecData...)
					switch dim {
					case "2D":
						points2D = append(points2D, vals)
					case "3D":
						points3D = append(points3D, vals)
					}
				}
			}
		}
	}
	log.Printf("2D points count: %d, 3D points count: %d", len(points2D), len(points3D))
}
```
</details>

The code produces this log output
<details><summary>Output</summary>

```
2024/01/11 12:59:47 created collection: d665d0ef-a6eb-42a2-a6b4-e64d2b8153fe
2024/01/11 12:59:47 upserted point: dc5725dc-a3b0-4236-8f75-9bab05a8a94b
2024/01/11 12:59:47 updating point: "dc5725dc-a3b0-4236-8f75-9bab05a8a94b" named vector: 2D, data: [1.1 2.2]
2024/01/11 12:59:47 updating point: "dc5725dc-a3b0-4236-8f75-9bab05a8a94b" named vector: 3D, data: [1.1 2.2 3.3]
2024/01/11 12:59:47 2D points count: 0, 3D points count: 1
```
</details>

This is also visible when you navigate to `qdrant` UI: you can only see `3D` point there, `2D` are never stored.

## Expected Behavior

I would expect to find both `3D` and `2D` vectors stored under the same point. Alas, no, as reproducible with the above Go code, only the `3D` points seem to be stored, which makes me think there is something strange. Does one vector override the other? 🤷‍♂️ Based on my understanding of the docs multiple named vectors should be allowed on the same point?

## Possible Solution

🤷‍♂️ Maybe this is expected behaviour? If yes I'd find it very strange and unintuitive. Or maybe I'm missing some mention in the docs? Any help would be appreciated!

## Context (Environment)

macOS, qdrant version `v1.7.3` run locally using docker ([v1.7.3](https://hub.docker.com/layers/qdrant/qdrant/v1.7.3/images/sha256-394249d41cf0d62e46aa65787f71f92a025aeacac05c1896ef7338cb358edff8?context=explore))

## Detailed Description

The above contains a sample Go code that can reproduce the reported issue.

## Possible Implementation

🤷‍♂️

**Comment by generall** [comment] 2024-01-11 08:50
Hi @milosgajdos, I think this is an intended behavior. The reason is following:

You are making 2 requests for inserting the same point and the second request overwrites the first one.

There are 2 possible solutions:


1. Make only one request with insertion of both vectors:

```
	Vectors: &pb.NamedVectors{
		Vectors: map[string]*pb.Vector{
			"2D": {
				Data: []float32{1.1, 2.2},
			},
			"3D": {
				Data: []float32{1.1, 2.2, 3.3},
			},
		},
	},
```

2. Replace second request with vector update instead of point upsert: https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/update_vectors

**Comment by timvisee** [comment] 2024-01-11 09:53
> I tend to make analogies with updating records in RDBMS, so maybe that's where I'm going wrong about this...

Though that's totally understandable, a vector database has wildly different semantics, so that may be something to be aware of.

Just to clarify in case that is confusing, there are points and vectors:

- a vector is a single _vector_ (a string of numbers like `[0.0, 3.0, 1.0]`)
- a point contains vector(s) and payload

Commonly, a point has just one vector. But in Qdrant you can use multiple vectors in a single point. The operations you use are actually point operations, meaning they operate on point level.

Naming in our API may be a bit off in some places, but sadly this is something we cannot change at this time due to backward compatibility.

In any case, this is definitely something we can better describe in our documentation.

> I'm confused by this. The code is actually calling UpdateVectors(ctx, &pb.UpdatePointVectors{}) 🤔 The only Upsert is the initial Point upsert. So what second request do you mean here?

I see you're already using this operation indeed. You still have two separate point entries however. While it shouldn't be a problem, maybe this is the culprit.

Could you try to see what happens if you combine both vectors in a single operation like this (untested):

```go
vectors := []*pb.PointVectors{
{
	Id: &pb.PointId{
		PointIdOptions: &pb.PointId_Uuid{
			Uuid: pointUID,
		},
	},
	Vectors: &pb.Vectors{
		VectorsOptions: &pb.Vectors_Vectors{
			Vectors: &pb.NamedVectors{
				Vectors: map[string]*pb.Vector{
					"2D": {
						Data: []float32{1.1, 2.2},
					},
					"3D": {
						Data: []float32{1.1, 2.2, 3.3},
					},
				},
			},
		},
	},
}
}
```

**Comment by milosgajdos** [comment] 2024-01-11 09:57
> Could you try to see what happens if you combine both vectors in a single operation like this (untested):

I've already verified this and it works like a charm, thanks.

> You still have two separate point entries however.

Indeed, though they're 2 entries for the same point i.e. point with the same `ID`. It seems to me that you can either update ALL named vectors on the same point or just a subset of them -- if you do the latter the ones you don't update in a single call "vanish"?

**Comment by timvisee** [comment] 2024-01-11 10:00
> I've already verified this and it works like a charm, thanks.

Fantastic! Thank you for confirming.

> Indeed, though they're 2 entries for the same point i.e. point with the same ID. It seems to me that you can either update ALL named vectors on the same point or just a subset of them -- if you do the latter the ones you don't update in a single call "vanish"?

Yeah I must admit I'm not quite sure what's going on here. I suspect there to be an update in our internal batching logic where it drops one of the two calls when it is structured this way.

I'll try to investigate this a bit later today :+1: 

Thank you for your report so far, and sorry for the inconvenience!

**Comment by timvisee** [comment] 2024-01-12 11:43
@milosgajdos I just tested the above, and there's a bug here indeed. I'll make sure to fix this as soon as possible. Thanks for catching it!

**Comment by timvisee** [comment] 2024-01-12 14:32
I've submitted a fix in <https://github.com/qdrant/qdrant/pull/3386>. It also has a bunch of tests, covering your exact case, to ensure this doesn't happen in the future.

**Comment by milosgajdos** [comment] 2024-01-13 00:49
Awesome!

**Comment by timvisee** [comment] 2024-01-15 09:08
<https://github.com/qdrant/qdrant/pull/3386> has just been merged and will be included in the next Qdrant release. :rocket:

**Closed by timvisee** 2024-01-15 09:08 UTC
Labels: bug
