### ISSUE TITLE
update_collection shows 'Can't reach one of the workers: channel closed'

### ISSUE THREAD

**Issue by AdirthaBorgohain** [qdrant/qdrant#1573] opened 2023-03-16 15:46 UTC
I uploaded around 36 million data to qdrant db after disabling the index like this:
```
client.recreate_collection(
    collection_name='my_collection', on_disk_payload=True,
    vectors_config=VectorParams(size=768, distance=Distance.DOT),
    optimizers_config=models.OptimizersConfigDiff(
        indexing_threshold=100000000,
        memmap_threshold=250000
    )
)
```
Once the data uploading was finished, I wanted to turn the indexing on with this code.
```
client.update_collection(
    collection_name='my_collection',
    optimizer_config=OptimizersConfigDiff(
        indexing_threshold=2000,
    ))
```
But whenever I run this code, I get the error:
```
client.update_collection(
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 1624, in update_collection
    result: Optional[bool] = self.http.collections_api.update_collection(
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 917, in update_collection
    return self._build_for_update_collection(
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py", line 479, in _build_for_update_collection
    return self.api_client.request(
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 68, in request
    return self.send(request, type_)
  File "/opt/conda/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 91, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 500 (Internal Server Error)
Raw response content:
b'{"result":null,"status":{"error":"Service internal error: Can\'t reach one of the workers: channel closed"},"time":0.000183709}'
```
What could be the reason for this? Am I doing something wrong?

My get_collection shows the following:
```
status=<CollectionStatus.RED: 'red'> optimizer_status=OptimizersStatusOneOf1(error='Service internal error: Removing segment which is still in use: "./storage/collections/sci_lit/0/segments/37a3c3d7-f250-40e0-998c-63b6085f9c1f"') vectors_count=37544846 indexed_vectors_count=0 points_count=37544846 segments_count=36 config=CollectionConfig(params=CollectionParams(vectors=VectorParams(size=384, distance=<Distance.DOT: 'Dot'>), shard_number=1, replication_factor=1, write_consistency_factor=1, on_disk_payload=True), hnsw_config=HnswConfig(m=16, ef_construct=100, full_scan_threshold=10000, max_indexing_threads=0, on_disk=False, payload_m=None), optimizer_config=OptimizersConfig(deleted_threshold=0.2, vacuum_min_vector_number=1000, default_segment_number=0, max_segment_size=None, memmap_threshold=100000, indexing_threshold=2000, flush_interval_sec=5, max_optimization_threads=1), wal_config=WalConfig(wal_capacity_mb=32, wal_segments_ahead=0)) payload_schema={}
```

**Comment by AdirthaBorgohain** [comment] 2023-03-16 18:02
Alright, thanks a lot. Is there a reason why this happens? And any solution as to how I can prevent it from happening again?

**Comment by agourlay** [comment] 2023-03-21 10:33
Proposing a workaround in https://github.com/qdrant/qdrant/pull/1595

@AdirthaBorgohain are you still running heavy search or inserts after decreasing `indexing_threshold`?

**Comment by generall** [comment] 2023-03-21 12:14
@AdirthaBorgohain we made some improvements, could you please try again with `dev` build? `docker pull qdrant/qdrant:dev`?

**Comment by AdirthaBorgohain** [comment] 2023-03-21 16:05
Sure I'll try it out and see if I get the same error again

**Comment by AdirthaBorgohain** [comment] 2023-03-21 16:07
> Proposing a workaround in #1595
> 
> @AdirthaBorgohain are you still running heavy search or inserts after decreasing `indexing_threshold`?

When I faced this issue, I wasn't even running any search. I just wanted to decrease `indexing_threshold` which led to this error. As for now, after I have restarted, I am running similarity searches while filtering by ids. Performance is fine most of the time but occasionally I do get timeout errors.

**Comment by agourlay** [comment] 2023-03-28 12:29
Thanks for the info, hopefully the fix will get you to a place where restarts are not needed :+1:

**Comment by generall** [comment] 2023-12-25 15:16
Assuming the issue is fixed in latest version

**Closed by generall** 2023-12-25 15:16 UTC
