### ISSUE TITLE
Troubleshooting Query Issues in Qdrant: Seeking Solutions for ID-Based Queries

### ISSUE THREAD

**Issue by Mohana-Murugan** [qdrant/qdrant#5635] opened 2024-12-10 13:36 UTC
Hi there !,

My exact issues are as follows
- I have stored the RAG PDF under: user_id: K5617, Agent_id: 5307, Company ID: 101. 
- I have stored the HR Policies under: user_id: K5618, Agent_id: 5308, Company ID: 102

It works fine:
![pic-1](https://github.com/user-attachments/assets/d978cff9-40c7-47ee-9fa9-1289751c61f1)
![pic-1](https://github.com/user-attachments/assets/6f01e109-3ef8-4c37-8c76-58af710cd6bb)

When IDs do not match:
![pic-1](https://github.com/user-attachments/assets/50c9ca34-f13c-4169-87da-cd8a1fe4d65a)

It provides the following wrong answer 
![pic-1](https://github.com/user-attachments/assets/f41474ae-80c9-4794-9f17-e3a1dbbf77ab)

 I am using the same embedding model, 'BAAI/bge-small-en-v1.5,' for storing and retrieving. However, I cannot identify the reason why I am getting these results.

When I pass this to the LLM, the model provides answers based on its pre-trained documents instead of retrieving information from Qdrant using a filter.

Without any filter, Qdrant works fine for us, and there is no doubt about that.

_Originally posted by @Mohana-Murugan in https://github.com/qdrant/qdrant/discussions/5594#discussioncomment-11515313_

**Comment by timvisee** [comment] 2024-12-10 16:06
This does not provide any new information.

Closing as duplicate of <https://github.com/qdrant/qdrant/issues/5633>.

**Closed by timvisee** 2024-12-10 16:06 UTC
