### ISSUE TITLE
Collections return 0 results even after inserting vectors

### ISSUE THREAD

**Issue by aseifert** [qdrant/qdrant#33] opened 2021-06-15 10:06 UTC
I tried to follow the instructions given in the [blog post](https://blog.qdrant.tech/neural-search-tutorial-3f034ab13adc) as close as possible, but the neural search always shows 0 results. At no point did I get any errors.

When querying the collection itself, `curl -s http://localhost:6333/collections/startups | jq .result.vectors_count` returns `0`.

The `./qdrant_storage` folder keeps growing as I insert records though.

Here's the full output of the collections endpoint:

```
{
  "result": {
    "status": "green",
    "vectors_count": 0,
    "segments_count": 5,
    "disk_data_size": 0,
    "ram_data_size": 0,
    "config": {
      "params": {
        "vector_size": 768,
        "distance": "Dot"
      },
      "hnsw_config": {
        "m": 16,
        "ef_construct": 100,
        "full_scan_threshold": 10000
      },
      "optimizer_config": {
        "deleted_threshold": 0.2,
        "vacuum_min_vector_number": 1000,
        "max_segment_number": 5,
        "memmap_threshold": 50000,
        "indexing_threshold": 20000,
        "payload_indexing_threshold": 10000,
        "flush_interval_sec": 10
      },
      "wal_config": {
        "wal_capacity_mb": 32,
        "wal_segments_ahead": 0
      }
    },
    "payload_schema": {}
  },
  "status": "ok",
  "time": 3.8746e-05
}
```

Kind regards,
Alex

**Comment by generall** [comment] 2021-06-15 11:12
Hi @aseifert, update operations are async by default, so error might happen after you receive confirmation of accepted request. I could not, however, reproduce it with demo setup. Folder growth happens due to the WAL, which logs all operations even is they are failed. 

In order to debug queries, you can force sync updates in API.

Can you please provide the result of update API https://qdrant.github.io/qdrant/redoc/index.html#operation/update_points with wait=true?

You can also do it with the following function in python:

```python
def _upload_batch(openapi_client: SyncApis, collection_name, batch):
    ids_batch, vectors_batch, payload_batch = batch
    return openapi_client.points_api.update_points(
        name=collection_name,
        collection_update_operations=PointOperationsAnyOf(
            upsert_points=PointInsertOperationsAnyOf(
                batch=PointInsertOperationsAnyOfBatch(
                    ids=ids_batch,
                    payloads=payload_batch,
                    vectors=vectors_batch
                )
            )
        ),
        wait=True
    )
```

**Comment by aseifert** [comment] 2021-06-16 12:36
I deleted the storage and started everything new. Trying to give you a minimal example (I am using [httpie](https://httpie.io/) instead of curl):

```
docker run -p 6333:6333 \
	-v $(pwd)/qdrant_storage:/qdrant/storage \
	generall/qdrant
echo '{"create_collection": {"name": "startups", "vector_size": 3, "distance": "Cosine"}}' | http POST "http://localhost:6333/collections"
http POST "http://localhost:6333/collections/startups?wait=true" < input.json
```

With the `input.json` being:

```
{
  "upsert_points": {
    "batch": {
      "ids": [
        0
      ],
      "payloads": [
        {
          "property1": "string",
          "property2": "string"
        }
      ],
      "vectors": [
        [
          0.1, 0.2, 0.3
        ]
      ]
    }
  }
}
```

The call to `create_collection` will work, while the POST to collections with `wait=true` will NOT work and will not even trigger a message from the middleware::logger. The call will hang, and even if I force exit with ctrl-c, every subsequent call e.g. to `GET /collections/startups` will hang too.

**Comment by generall** [comment] 2021-06-16 13:04
Unfortunately I could not reproduce this on my machine:

```
avasnetsov@avasnetsov-ThinkPad-E490 ~/tmp ➜ echo '{"create_collection": {"name": "startups", "vector_size": 3, "distance": "Cosine"}}' | http POST "http://localhost:6333/collections"
HTTP/1.1 200 OK
content-length: 48
content-type: application/json
date: Wed, 16 Jun 2021 12:51:20 GMT

{
    "result": true,
    "status": "ok",
    "time": 0.695834272
}

avasnetsov@avasnetsov-ThinkPad-E490 ~/tmp ➜ cat input.json | jq
{
  "upsert_points": {
    "batch": {
      "ids": [
        0
      ],
      "payloads": [
        {
          "property1": "string",
          "property2": "string"
        }
      ],
      "vectors": [
        [
          0.1,
          0.2,
          0.3
        ]
      ]
    }
  }
}
avasnetsov@avasnetsov-ThinkPad-E490 ~/tmp ➜ http POST "http://localhost:6333/collections/startups?wait=true" < input.json
HTTP/1.1 200 OK
content-length: 83
content-type: application/json
date: Wed, 16 Jun 2021 12:52:36 GMT

{
    "result": {
        "operation_id": 0,
        "status": "completed"
    },
    "status": "ok",
    "time": 0.000233178
}

avasnetsov@avasnetsov-ThinkPad-E490 ~/tmp ➜ http GET 'http://localhost:6333/collections/startups'
HTTP/1.1 200 OK
content-length: 534
content-type: application/json
date: Wed, 16 Jun 2021 12:53:25 GMT

{
    "result": {
        "config": {
            "hnsw_config": {
                "ef_construct": 100,
                "full_scan_threshold": 10000,
                "m": 16
            },
            "optimizer_config": {
                "deleted_threshold": 0.2,
                "flush_interval_sec": 10,
                "indexing_threshold": 20000,
                "max_segment_number": 5,
                "memmap_threshold": 50000,
                "payload_indexing_threshold": 10000,
                "vacuum_min_vector_number": 1000
            },
            "params": {
                "distance": "Cosine",
                "vector_size": 3
            },
            "wal_config": {
                "wal_capacity_mb": 32,
                "wal_segments_ahead": 0
            }
        },
        "disk_data_size": 0,
        "ram_data_size": 0,
        "segments_count": 5,
        "status": "green",
        "vectors_count": 1
    },
    "status": "ok",
    "time": 2.2191e-05
}
```

```
docker run -p 6333:6333 \ 
        -v $(pwd)/qdrant_storage:/qdrant/storage \
        generall/qdrant
[2021-06-16T12:50:44Z INFO  actix_server::builder] Starting 8 workers
[2021-06-16T12:50:44Z INFO  actix_server::builder] Starting "actix-web-service-0.0.0.0:6333" service on 0.0.0.0:6333
[2021-06-16T12:51:20Z INFO  wal::segment] Segment { path: "./storage/collections/startups/wal/open-1", entries: 0, space: (8/33554432) }: created
[2021-06-16T12:51:20Z INFO  wal] Wal { path: "./storage/collections/startups/wal", segment-count: 1, entries: [0, 0)  }: opened
[2021-06-16T12:51:20Z INFO  wal::segment] Segment { path: "./storage/collections/startups/wal/open-2", entries: 0, space: (8/33554432) }: created
[2021-06-16T12:51:20Z INFO  actix_web::middleware::logger] 172.17.0.1:52932 "POST /collections HTTP/1.1" 200 48 "-" "HTTPie/0.9.8" 0.696029
[2021-06-16T12:52:36Z INFO  actix_web::middleware::logger] 172.17.0.1:52952 "POST /collections/startups?wait=true HTTP/1.1" 200 83 "-" "HTTPie/0.9.8" 0.000310
[2021-06-16T12:53:25Z INFO  actix_web::middleware::logger] 172.17.0.1:52966 "GET /collections/startups HTTP/1.1" 200 534 "-" "HTTPie/0.9.8" 0.000058
```

Could you please make sure that you are using the latest version (remove it from docker images and download again)?
Would you also mind sharing what operation system do you use?

**Comment by aseifert** [comment] 2021-06-16 13:54
Alright I think I got it: The issue seems to be due to the fact that I only have 1 CPU on my cloud machine. When I run it on my laptop (with 4 workers) it works.

**Comment by generall** [comment] 2021-06-20 17:51
Should be fixed in https://github.com/qdrant/qdrant/releases/tag/v0.3.4

**Closed by generall** 2021-06-20 17:51 UTC
Labels: bug
