### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by zhangzf875** [qdrant/qdrant#3772] opened 2024-03-05 03:47 UTC
I have 40 collections on qdrant installed with version 1.7.2, and the memory of the server is 5G. I will optimize the collection through the official document and update the configuration information of these 40 collections:
PATCH /collections/collection_name
{
"optimizers_config": {
"memmap_threshold": 20000
}
}
After the update, it is found that the memory occupied by the server is still unchanged, what is the reason for this, and how to optimize the collection memory usage?
In qdrant, how to find out which collection uses more memory, and how to improve this?

**Comment by generall** [comment] 2024-03-05 13:00
Have you considered this approach - https://qdrant.tech/documentation/guides/multiple-partitions/ ?

**Comment by zhangzf875** [comment] 2024-03-07 02:08
发现上面那个方法对改善内存用量没有作用呢，现在qdrant内存使用已经超过阈值90%，现在还有什么方法可以减少内存使用量

**Comment by generall** [comment] 2024-03-20 10:13
Memory usage you see might be due to disk cache, it is to be expected. I would need a bit more details to answer exactly.

**Comment by generall** [comment] 2024-04-23 21:00
hey @zhangzf875, I am going to close this issue as we can't reproduce the problem without additional information.

For the context, here are some more info on proper memory measurement and optimization:  https://qdrant.tech/articles/memory-consumption/

**Closed by generall** 2024-04-23 21:00 UTC
