### ISSUE TITLE
Timeout Requests when usage on the server is high

### ISSUE THREAD

**Issue by MasoudKaviani** [qdrant/qdrant#1765] opened 2023-04-21 12:05 UTC
Hello, I have a Quadrant server with approximately 150,000,000 vectors, each of them with a length of 99.
I am using a Python HTTP client.
The problem arises when the server is under high load, and during that time, requests will throw timeouts. Even after the server load returns to normal, the timeout problem persists until we restart the Qdrant Docker container. After restarting the docker container, the problem is resolved.

**Comment by generall** [comment] 2023-04-27 06:44
hi @MasoudKaviani , thanks for reporting that! Could you please share any additional details about your setup so we could try to reproduce that problem on our side?


- what is hardware you are using?
- what is the collection settings: is there a payload, is mmap used, is quantization used, e.t.c.
- what query params are you using
- any unusual details?

**Comment by MasoudKaviani** [comment] 2023-04-29 06:04
Hi @generall 
The Hardware: 32core CPU, 500G RAM, SSD
Collection Settings: No payload, no mmap and all other settings are default config.yaml setting
Query Params: Simply inserting about 4000 vectors, each of them with length of 99
HTTP Request

**Comment by generall** [comment] 2023-06-27 10:01
Might be related: https://github.com/qdrant/qdrant/issues/2141

**Comment by agourlay** [comment] 2023-08-30 13:54
@MasoudKaviani any new information while running on newer versions?

**Comment by generall** [comment] 2023-12-10 17:22
Assuming the problem is resolved in a newer version.
Please feel free to re-open it if there are any new data.

**Closed by generall** 2023-12-10 17:22 UTC
