### ISSUE TITLE
Shard Not Active Error

### ISSUE THREAD

**Issue by yusufani** [qdrant/qdrant#4027] opened 2024-04-12 11:19 UTC
Hi, 
I am trying to implement distributed qdrant. I have already qdrant with several collections and cluster INFO looks like this: 
```
{
  "result": {
    "status": "enabled",
    "peer_id": 2979974762066354,
    "peers": {
      "2979974762066354": {
        "uri": "http://172.31.24.252:6335/"
      },
      "1418878837160198": {
        "uri": "http://172.31.24.177:6335/"
      }
    },
    "raft_info": {
      "term": 9607,
      "commit": 257,
      "pending_operations": 0,
      "leader": 2979974762066354,
      "role": "Leader",
      "is_voter": true
    },
    "consensus_thread_status": {
      "consensus_thread_status": "working",
      "last_update": "2024-04-10T14:48:21.798830364Z"
    },
    "message_send_failures": {}
  },
  "status": "ok",
  "time": 0.00000901
}
```

I updated my collections replication factor to 2, and I want to have 2 nodes with 1 replace each. So I want to copy my shards to new node by following command: 
```
POST /collections/test_collection/cluster
{
  "replicate_shard": {
    "shard_id": 0,
    "from_peer_id": 2979974762066354,
    "to_peer_id": 1418878837160198
  }
}

```
but I got this error: 
```
{
  "error": "Bad request: Shard 0 is not active on peer 2979974762066354"
}
```
Error as a log: 
`
2024-04-10T14:52:56.673689Z  WARN storage::content_manager::consensus_manager: Failed to apply collection meta operation entry with user error: Bad request: Shard 0 is not active on peer 2979974762066354    
`

However, it looks active when I look info section from qdrant web UI.  Any idea why I am getting this error ?
![image](https://github.com/qdrant/qdrant/assets/35346311/58448622-08f6-4b2d-9fc5-2cda5ea07871)

Leader node version : v1.8.1
Follower node version : 1.8.4
Both served on docker containers in differrent servers

**Comment by generall** [comment] 2024-04-13 09:15
Hey @yusufani, we would need a detailed info on how exactly did you set up your distributed cluster, and also how the consensus looks like on both nodes.

But tbh, maintaining self-made distributed clusters proves to be a complicated task, so I would recommend to either use our open-source helm chart https://github.com/qdrant/qdrant-helm for kubernetes, or simply the cloud version, where distributed deployment works out of the box.

**Comment by generall** [comment] 2024-04-23 19:56
Hey @yusufani, I am going to close this issue for now. If you have more information on how to reproduce the problem, please feel free to re-open it

**Closed by generall** 2024-04-23 19:56 UTC
