### ISSUE TITLE
Unable to insert a document with a list of integers

### ISSUE THREAD

**Issue by ruslaniv** [qdrant/qdrant#2655] opened 2023-09-13 09:31 UTC
I'm trying to insert a dataframe into a Quadrant vector database using this code:

```python
client.upsert(
    collection_name="props",
    points=[
        rest.PointStruct(
            id=doc["id"],
            vector={
                "embedding": doc["embedding"],
            },
            payload=doc[['id', 'user_id', 'title', 'seo_friendly', 'rubrics']].to_dict(),
        )
        for idx, doc in df.iterrows()
    ],
)
```
The index is configured as follows:

```python
vector_size = 1024

client.recreate_collection(
    collection_name="props",
    vectors_config={
        "embedding": rest.VectorParams(
            distance=rest.Distance.COSINE,
            size=vector_size,
        ),
    },
    optimizers_config=rest.OptimizersConfigDiff(
        indexing_threshold=0,
    ),
    shard_number=4,

)
```
## Current Behavior

I'm getting an error on the first row of the dataframe:

```shell
ValueError: Not supported json value: [3467]
```

## Steps to Reproduce
1. Try to insert a document with a list of integer values in the index 

## Expected Behavior
A list if ints should be inserted as a payload

## Context (Environment)
I need to store a list in ints that represents a list of rubrics the document I'm indexing belongs to

**Comment by timvisee** [comment] 2023-09-13 12:12
I'm not sure where this error message is coming from:

```
ValueError: Not supported json value: [3467]
```

Could it be that

```python
doc["embedding"] == [3467]
```

in

```python
vector={
    "embedding": doc["embedding"],
},
```
?

In that case the mapping of your embedding is wrong.

**Comment by ruslaniv** [comment] 2023-09-14 05:35
I probably should have included the stack trace, sorry.

<details><summary>Here is the full stack trace:</summary>

```shell

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

File [~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/qdrant_client.py:776](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ruslan/codebase/suplbiz/datascience/notebooks/~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/qdrant_client.py:776), in QdrantClient.upsert(self, collection_name, points, wait, ordering, **kwargs)
    752 """Update or insert a new point into the collection.
    753 
    754 If point with given ID already exists - it will be overwritten.
   (...)
    772     Operation result
    773 """
    774 assert len(kwargs) == 0, f"Unknown arguments: {list(kwargs.keys())}"
--> 776 return self._client.upsert(
    777     collection_name=collection_name,
    778     points=points,
    779     wait=wait,
    780     ordering=ordering,
    781     **kwargs,
    782 )

File [~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/qdrant_remote.py:1015](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ruslan/codebase/suplbiz/datascience/notebooks/~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/qdrant_remote.py:1015), in QdrantRemote.upsert(self, collection_name, points, wait, ordering, **kwargs)
   1004     points = [
   1005         grpc.PointStruct(
   1006             id=RestToGrpc.convert_extended_point_id(points.ids[idx]),
   (...)
   1012         for idx in range(len(points.ids))
   1013     ]
   1014 if isinstance(points, list):
-> 1015     points = [
   1016         RestToGrpc.convert_point_struct(point)
   1017         if isinstance(point, models.PointStruct)
   1018         else point
   1019         for point in points
   1020     ]
   1022 if isinstance(ordering, models.WriteOrdering):
   1023     ordering = RestToGrpc.convert_write_ordering(ordering)

File [~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/qdrant_remote.py:1016](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ruslan/codebase/suplbiz/datascience/notebooks/~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/qdrant_remote.py:1016), in <listcomp>(.0)
   1004     points = [
   1005         grpc.PointStruct(
   1006             id=RestToGrpc.convert_extended_point_id(points.ids[idx]),
   (...)
   1012         for idx in range(len(points.ids))
   1013     ]
   1014 if isinstance(points, list):
   1015     points = [
-> 1016         RestToGrpc.convert_point_struct(point)
   1017         if isinstance(point, models.PointStruct)
   1018         else point
   1019         for point in points
   1020     ]
   1022 if isinstance(ordering, models.WriteOrdering):
   1023     ordering = RestToGrpc.convert_write_ordering(ordering)

File [~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/conversions/conversion.py:1326](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ruslan/codebase/suplbiz/datascience/notebooks/~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/conversions/conversion.py:1326), in RestToGrpc.convert_point_struct(cls, model)
   1321 @classmethod
   1322 def convert_point_struct(cls, model: rest.PointStruct) -> grpc.PointStruct:
   1323     return grpc.PointStruct(
   1324         id=cls.convert_extended_point_id(model.id),
   1325         vectors=cls.convert_vector_struct(model.vector),
-> 1326         payload=cls.convert_payload(model.payload) if model.payload is not None else None,
   1327     )

File [~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/conversions/conversion.py:1331](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ruslan/codebase/suplbiz/datascience/notebooks/~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/conversions/conversion.py:1331), in RestToGrpc.convert_payload(cls, model)
   1329 @classmethod
   1330 def convert_payload(cls, model: rest.Payload) -> Dict[str, grpc.Value]:
-> 1331     return dict((key, json_to_value(val)) for key, val in model.items())

File [~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/conversions/conversion.py:1331](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ruslan/codebase/suplbiz/datascience/notebooks/~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/conversions/conversion.py:1331), in <genexpr>(.0)
   1329 @classmethod
   1330 def convert_payload(cls, model: rest.Payload) -> Dict[str, grpc.Value]:
-> 1331     return dict((key, json_to_value(val)) for key, val in model.items())

File [~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/conversions/conversion.py:36](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ruslan/codebase/suplbiz/datascience/notebooks/~/codebase/venvs/datascience-Gn54_afE-py3.11/lib/python3.11/site-packages/qdrant_client/conversions/conversion.py:36), in json_to_value(payload)
     32 if isinstance(payload, dict):
     33     return Value(
     34         struct_value=Struct(fields=dict((k, json_to_value(v)) for k, v in payload.items()))
     35     )
---> 36 raise ValueError(f"Not supported json value: {payload}")

ValueError: Not supported json value: [3467]

```
</details> 

But basically it failed here: `/qdrant_client/conversions/conversion.py:1331` trying to `return dict((key, json_to_value(val)) for key, val in model.items())`

Here is the first row of the df I was processing:
<img width="630" alt="image" src="https://github.com/qdrant/qdrant/assets/7631314/bfff0899-9926-4aac-96c4-3d75863c84be">

**Comment by ruslaniv** [comment] 2023-09-14 06:39
Ah, got it! 
```python
print(type(doc.to_dict()['rubrics']))
>>> <class 'numpy.ndarray'>
```
after casting in to `list`, it worked just fine.

Was there a specific reason to not support numpy arrays?

**Comment by timvisee** [comment] 2023-09-14 08:43
Happy to see you were able to fix it!

> Was there a specific reason to not support numpy arrays?

To be honest, I have no idea. I'll ask one of our Python client guys.

**Comment by timvisee** [comment] 2023-09-14 09:04
Asked internally. Not very concrete, but we basically have the following three reasons (thanks @joein):

- Numpy arrays need to be converted either way to send them as JSON
- We don't want to support every available array type
- Our `PointStruct` code is auto generated

I'll close this now as the issue is fixed. Please feel free to open it again if you have further questions.

**Closed by timvisee** 2023-09-14 09:04 UTC
Labels: bug

**Comment by joein** [comment] 2023-09-14 09:14
@ruslaniv you can use np arrays in some of the methods though, like `upload_collection`. 

All the methods are type-annotated and we expect a user to check it before using or IDE to highlight usage of incorrect types, however I can confirm that in this particular case with `Dict` IDE doesn't highlight it :(

I can also agree that the error is not self-explanatory, will try to make it more user-friendly
