### ISSUE TITLE
Allow dashboard to be hosted with URL prefix

### ISSUE THREAD

**Issue by tekumara** [qdrant/qdrant#4618] opened 2024-07-05 11:42 UTC
When qdrant is accessed via ingress with a path prefix, eg: http://myingress.mydomain/qdrant/ the dashboard fails to load because the asset URLs are absolute not relative. 

eg: the dashboard links to /dashboard/assets/index-9f39229a.js and so the browser tries to fetch http://myingress.mydomain/dashboard/assets/index-9f39229a.js which fails.

**Comment by xzfc** [comment] 2024-07-05 18:53
I believe it's a duplicate of https://github.com/qdrant/qdrant-web-ui/issues/94.

**Closed by xzfc** 2024-07-05 18:53 UTC
