### ISSUE TITLE
panic: neither $XDG_CONFIG_HOME nor $HOME are defined when installing Qdrant Agent on Kubernetes 1.30.3

### ISSUE THREAD

**Issue by dev-ago** [qdrant/qdrant#4967] opened 2024-08-27 16:11 UTC
Hier ist das beschriebene Problem in ein GitHub-Issue-Template umgeschrieben:

---

**Title:** `panic: neither $XDG_CONFIG_HOME nor $HOME are defined` when installing Qdrant Agent on Kubernetes 1.30.3

## Current Behavior
When installing the Qdrant Agent on Kubernetes version 1.30.3, the container fails to start and exits with the following error message:
```
panic: neither $XDG_CONFIG_HOME nor $HOME are defined

goroutine 1 [running]:
github.com/notaryproject/notation-go/dir.loadUserPath()
    /go/pkg/mod/github.com/notaryproject/notation-go@v1.1.0/dir/path.go:85 +0xc5
github.com/notaryproject/notation-go/dir.init.0()
    /go/pkg/mod/github.com/notaryproject/notation-go@v1.1.0/dir/path.go:77 +0xf
Stream closed EOF for qdrant/qdrant-cloud-agent-fb86cb499-72q9k (qdrant-cloud-agent)
```
Interestingly, the same installation with identical values works without any issues on a Kubernetes 1.27.10 cluster.

## Steps to Reproduce
1. Install the Qdrant Cloud Agent using Helm on a Kubernetes 1.30.3 cluster with the following command:
   ```bash
   helm upgrade --install qdrant-cloud-agent 'oci://registry.cloud.qdrant.io/qdrant-charts/qdrant-cloud-agent' --version=1.2.5 --namespace qdrant --set podAnnotations.accessKeyHash=MYHASHVALUES --set-json config='{"serverURL": "https://cloud.qdrant.io", "accountId": "MYACCOUNTID", "regionId": "MY-REGION-ID"}' --set-json image='{"repository": "registry.cloud.qdrant.io/qdrant/qdrant-cloud-agent"}' --set-json imagePullSecrets='[{"name": "qdrant-registry-creds"}]'
   ```
2. Observe that the container fails to start and logs the above error.

## Expected Behavior
The Qdrant Agent should start successfully without encountering the `$XDG_CONFIG_HOME` or `$HOME` error on Kubernetes 1.30.3, as it does on version 1.27.10.

## Context (Environment)
- **Kubernetes Version:** 1.30.3
- **Qdrant Cloud Agent Version:** 1.2.5
- **Previous Working Kubernetes Version:** 1.27.10

The error disrupts our deployment pipeline, and we are unable to start the Qdrant Agent on our newer Kubernetes cluster.

## Detailed Description
This issue appears to be related to environment variables `$XDG_CONFIG_HOME` or `$HOME` not being set in the container environment on Kubernetes 1.30.3. The same configuration works without issues on Kubernetes 1.27.10. The underlying cause might be related to changes in Kubernetes behavior or security context handling between these versions.

**Comment by generall** [comment] 2024-08-27 17:24
Hey @dev-ago!

Qdrant Agent is not part of this repository. If you are talking about hybrid cloud agent, I will try to forward your question

**Comment by bashofmann** [comment] 2024-08-28 15:30
@dev-ago the issue is fixed now with a new version of the agent.

Since your agent never connected, it can't automatically update itself. You can manually update the existing environment by:
* Going to the detail page of your Hybrid Cloud environment
* Under Actions choose "Rotate secret"
* Confirm that you rotate the secret
* Execute the printed kubectl and helm install commands to update the secrets and upgrade the agent to the new version.

**Closed by bashofmann** 2024-08-28 15:30 UTC
Labels: bug
