### ISSUE TITLE
Flaky test_collection_creation_after_dropping test

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3254] opened 2023-12-19 16:21 UTC
https://github.com/qdrant/qdrant/actions/runs/7264432083/job/19791956029?pr=3251
https://github.com/qdrant/qdrant/actions/runs/7346890187/job/20002395601?pr=3296

**Comment by timvisee** [comment] 2024-01-03 09:26
Duplicate of <https://github.com/qdrant/qdrant/issues/2616>

**Closed by timvisee** 2024-01-03 09:26 UTC
Labels: bug
