### ISSUE TITLE
webui：Page not found

### ISSUE THREAD

**Issue by WGS-note** [qdrant/qdrant#4720] opened 2024-07-22 07:58 UTC
I started the qdrant service with the following command:

```shell
docker run --rm --name qdrant \
    -p 6333:6333 -p 6334:6334 \
    -v $(pwd)/qdrant_storage:/qdrant/storage \
    qdrant/qdrant:latest
```

The console prints the following:

```shell
           _                 _    
  __ _  __| |_ __ __ _ _ __ | |_  
 / _` |/ _` | '__/ _` | '_ \| __| 
| (_| | (_| | | | (_| | | | | |_  
 \__, |\__,_|_|  \__,_|_| |_|\__| 
    |_|                           

Version: 1.10.1, build: 4aac0231
Access web UI at http://localhost:6333/dashboard

2024-07-22T07:19:06.530640Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json    
2024-07-22T07:19:06.585439Z  INFO storage::content_manager::toc: Loading collection: test_collection    
2024-07-22T07:19:06.633192Z  INFO collection::shards::local_shard: Recovering collection test_collection: 0/1 (0%)    
2024-07-22T07:19:06.645884Z  INFO collection::shards::local_shard: Recovered collection test_collection: 1/1 (100%)    
2024-07-22T07:19:06.647115Z  INFO qdrant: Distributed mode disabled    
2024-07-22T07:19:06.647137Z  INFO qdrant: Telemetry reporting enabled, id: 5460e3a0-259b-4df3-868b-9b1168b5d7a2    
2024-07-22T07:19:06.654221Z  INFO qdrant::actix: TLS disabled for REST API    
2024-07-22T07:19:06.654562Z  INFO qdrant::actix: Qdrant HTTP listening on 6333    
2024-07-22T07:19:06.654591Z  INFO actix_server::builder: Starting 55 workers
2024-07-22T07:19:06.654601Z  INFO actix_server::server: Actix runtime found; starting in Actix runtime
2024-07-22T07:19:06.656141Z  INFO qdrant::tonic: Qdrant gRPC listening on 6334    
2024-07-22T07:19:06.656167Z  INFO qdrant::tonic: TLS disabled for gRPC API 
```

Then, I accessed webui in the browser and replaced localhost with the IP of the server:

```shell
http://172.16.1.69:6333/dashboard
```

At this point, the console prints:

```shell
2024-07-22T07:19:26.381468Z  INFO actix_web::middleware::logger: 172.17.0.1 "GET /dashboard HTTP/1.1" 404 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" 0.000158    
```

And the browser cannot open the web page:
```shell
Page not found for 172.16.1.69 A page corresponding to the following URL was not found：http://172.16.1.69:6333/dashboard

HTTP ERROR 404
```

what do I do?

**Comment by timvisee** [comment] 2024-07-22 08:36
Does it work with `localhost` if you're using `--network=host`?

Maybe the local IPs are mixed up. I've not seen this before. Is the last snippet shown in plain text, or does your browser render it as proper error page?

**Comment by WGS-note** [comment] 2024-07-22 08:50
Hi, I don't understand your description. The console is already able to receive access, but it is not finding the dashboard page!

**Comment by WGS-note** [comment] 2024-07-22 08:53
I run:

```shell
curl -H "Authorization: Bearer 123456" http://172.16.1.69:6333/collections
```

Able to return:
```
{"result":{"collections":[{"name":"test_collection"}]},"status":"ok","time":0.000027697}%      
```

 But it's just not accessible：`http://172.16.1.69:6333/dashboard`

**Comment by timvisee** [comment] 2024-07-22 08:59
I cannot reproduce this. Using the direct container IP does not show problems for me.

You show that the above request works with curl. Does `GET http://172.16.1.69:6333/collections` work fine in your browser?

**Comment by timvisee** [comment] 2024-07-22 09:05
Great!

Happy you were able to resolve this. Closing this as I assume there are no further questions.

**Closed by timvisee** 2024-07-22 09:05 UTC
Labels: bug
