### ISSUE TITLE
Showing creation time as None after creating Snapshot 

### ISSUE THREAD

**Issue by ramchennuru** [qdrant/qdrant#3427] opened 2024-01-19 11:10 UTC
After creation of collection, injected the data in the collection and trying to create Snapshot.But,it was showing creation time as None.

**code:**
`def create_snapshot(collection_name="test_collection"):
    url = f'{qdrant_url}/collections/{collection_name}/snapshot'
    headers = {
        'Authorization': f'Bearer {qdrant_api_key}',
        'Content-Type': 'application/json'
    }
    print("URL is: ", url)
    try:
        response = requests.post(url, headers=headers)

        if response.status_code == 200:
            print("Snapshot created successfully")
        else:
            print(f"Error: {response.status_code}, {response.text}")

    except Exception as e:
        print(f"An exception occurred: {e}")`

I have taken qdrant image and deployed in GCP
the env variables are:
`QDRANT__SERVICE__API_KEY`=""
`QDRANT__STORAGE__SNAPSHOTS_PATH`=""

**Comment by generall** [comment] 2024-01-19 13:50
could you pls share what exactly was the result of executing this script?

**Comment by ramchennuru** [comment] 2024-01-19 14:09
`Snapshot created successfully {'result': {'name': 'test_collection-8355533117942707-2024-01-19-14-08-07.snapshot', 'creation_time': None, 'size': 67518464}, 'status': 'ok', 'time': 0.376291927}`
the above output that I was getting if I run the above script

**Comment by ramchennuru** [comment] 2024-01-19 14:12
while iam hitting get snapshot api getting below error

`index-9558a693.js:40 TypeError: Cannot read properties of null (reading 'valueOf')
    at index-9558a693.js:1502:11214
    at Array.map (<anonymous>)
    at XMe (index-9558a693.js:1502:11132)
    at EX (index-9558a693.js:38:19598)
    at lj (index-9558a693.js:40:3155)
    at pCe (index-9558a693.js:40:45029)
    at hCe (index-9558a693.js:40:39950)
    at N6e (index-9558a693.js:40:39873)
    at e4 (index-9558a693.js:40:39723)
    at bj (index-9558a693.js:40:36071)`

**Comment by SSK-14** [comment] 2024-01-22 07:03
Facing the same issue in cloud [ Deployed qdrant in GCP cloud run ].
But in local it seems to be working !

**Comment by generall** [comment] 2024-01-22 09:00
Could you please share which versions of server and client are you using?

**Comment by SSK-14** [comment] 2024-01-22 09:23
> Could you please share which versions of server and client are you using?

Using server version : v1.7.3 
Accessing qdrant via http !

**Comment by timvisee** [comment] 2024-01-22 15:49
I have been seeing the same on my system, but haven't had the time yet to look into the root cause for it.

I did open <https://github.com/qdrant/qdrant-web-ui/pull/146> for it to prevent our web UI from crashing when this happens.

@ramchennuru @SSK-14 Could you please describe what file system you're running this on? It might have something to do this with, because I'm running it on a weird file system myself.

**Comment by SSK-14** [comment] 2024-01-23 05:16
Sure! I'm using Google Cloud Run, where the file system is abstracted. Thanks for opening the issue.

**Comment by generall** [comment] 2024-04-23 21:48
web-ui issue should be fixed by now. But the None value in the API response, I believe, is due to the fact that not all file systems can actually report that. I consider this issue resolved

**Closed by generall** 2024-04-23 21:48 UTC
Labels: bug
