### ISSUE TITLE
Implement Jaccard Distance

### ISSUE THREAD

**Issue by zzzz-vincent** [qdrant/qdrant#1496] opened 2023-02-24 06:47 UTC
**Is your feature request related to a problem? Please describe.**
I was attempting to work on adding Jaccard Distance and would like to make this issue for further disussion.

**Describe the solution you'd like**
1) preprocess: nothing

2) similarity: 
First, convert f32 values in vectors to bit and store as set1 and set2.
Then, compute set1.intersection(set2).len() / set1.intersection(set2).len() as similarity

3) postprocess: nothing

**Describe alternatives you've considered**
However, proposed implementation above leads to an issue that it is not likely f32 vector should have two exactly same float values. If I am correct, in most case, Jaccard Index is used for text level evaluation such as ["cat", "dog", "pig"] & ["cat", "bird"] -> 1 / 4 = 0.25.

**Additional context**
Project for Google Summer of Code

**Comment by TmLev** [comment] 2023-03-04 01:45
Isn't this a duplicate of #1319?

**Comment by generall** [comment] 2023-05-24 11:29
This issue is currently out-of-score for our Roadmap, please feel free to re-open it if there are some additional use-cases for this distance metric

**Closed** 2023-05-24 11:29 UTC
Labels: wontfix
