### ISSUE TITLE
Searching based on a non vector query

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant#1937] opened 2023-05-21 03:59 UTC
How do I do searches in qdrant purely based on non vector fields in the query??

**Comment by generall** [comment] 2023-05-21 09:05
https://qdrant.tech/documentation/points/#scroll-points

**Comment by nairajay2k** [comment] 2023-05-24 02:52
This is one search result corresponding to schema.
ScoredPoint(id='ef72218e-c3a0-4177-87cd-92d7c715e12b', version=49618, score=539.0775, payload={'claim_number': '00001', 'dependent_on': None, 'file_name': 'check.XML.out',  'is_dependent': 'false', 'snippet': '1.  such that', 'score': 539.0775}, vector=[0.1,0.2,0.1])
And this is how Im retrieving the count
count = client.count(
    collection_name=coll_name, 
        must=[
            models.FieldCondition(
                key="is_dependent", 
                match=models.MatchValue(value="true")
            ),
        ],
    exact=True,
)
However the count is constant and doesnt seem to depend on what key and value I specify in match condition. What am I doing wrong??

**Comment by generall** [comment] 2023-06-09 08:58
@nairajay2k, please provide a reproducible example, a script we can run and see the problem. We can't determine the reason of the problem with the example you provided

**Comment by generall** [comment] 2023-12-10 17:13
I am going to close it for now, please feel free to re-open if there are any additional details

**Closed by generall** 2023-12-10 17:13 UTC
Labels: can't reproduce

**Comment by TimPietrusky** [comment] 2024-03-07 13:53
If anyone is looking for this, the exact URL is now https://qdrant.tech/documentation/concepts/points/#scroll-points
