### ISSUE TITLE
HTTP stop responding after some time

### ISSUE THREAD

**Issue by starinacool** [qdrant/qdrant#2353] opened 2023-07-29 02:13 UTC
Qdrant stops responding after some time with normal workload.

## Current Behavior
HTTP requests hangs forever

## Steps to Reproduce
1. Load data with upsert requests about 26 000 000 points
2. Start requesting via recommend endpoint (20 rps) while keep upserting new data (3 rps average)

Collection:

```json
{
  "result": {
    "status": "green",
    "optimizer_status": "ok",
    "vectors_count": 26434783,
    "indexed_vectors_count": 26423555,
    "points_count": 26434783,
    "segments_count": 13,
    "config": {
      "params": {
        "vectors": {
          "size": 312,
          "distance": "Cosine",
          "hnsw_config": {
            "m": 64,
            "ef_construct": 512,
            "on_disk": true
          },
          "quantization_config": {
            "scalar": {
              "type": "int8",
              "quantile": 0.99,
              "always_ram": false
            }
          },
          "on_disk": true
        },
        "shard_number": 1,
        "replication_factor": 1,
        "write_consistency_factor": 1,
        "on_disk_payload": true
      },
      "hnsw_config": {
        "m": 64,
        "ef_construct": 512,
        "full_scan_threshold": 10000,
        "max_indexing_threads": 0,
        "on_disk": true
      },
      "optimizer_config": {
        "deleted_threshold": 0.2,
        "vacuum_min_vector_number": 1000,
        "default_segment_number": 0,
        "max_segment_size": null,
        "memmap_threshold": null,
        "indexing_threshold": 20000,
        "flush_interval_sec": 5,
        "max_optimization_threads": 1
      },
      "wal_config": {
        "wal_capacity_mb": 32,
        "wal_segments_ahead": 0
      },
      "quantization_config": null
    },
    "payload_schema": {
      "a": {
        "data_type": "integer",
        "points": 26434783
      }
    }
  },
  "status": "ok",
  "time": 0.001014069
}
```

3
```
# telnet 10.0.245.6 6333
Trying 10.0.245.6...
Connected to 10.0.245.6.
Escape character is '^]'.
GET /collections
```

Hangs forever

## Expected Behavior
HTTP interface works as expected

## Possible Solution
Not known

## Context (Environment)
`
> lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
32Gb, NVMe SSD, Hetzner VM 16 ADM cores.
`
`
docker run -p 6333:6333 -v /var/qdrant_storage:/qdrant/storage -e QDRANT__LOG_LEVEL=DEBUG qdrant/qdrant
`

## Detailed Description
Fix this hang, please

**Comment by starinacool** [comment] 2023-07-29 02:15
Tried to run with DEBUG log level. No relevant messages in the log.

**Comment by starinacool** [comment] 2023-07-29 03:38
Upserting in batches of 200 points.

**Comment by starinacool** [comment] 2023-07-29 08:49
Console output:

`
{
  "message": "Network Error",
  "name": "AxiosError",
  "stack": "AxiosError: Network Error\n    at c.onerror (https://**********/dashboard/assets/index-92508d58.js:242:4394)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json"
    },
    "method": "get",
    "url": "collections/items-rubert-tiny2/cluster",
    "data": "{}"
  },
  "code": "ERR_NETWORK",
  "status": null
}
`

**Comment by starinacool** [comment] 2023-07-30 07:02
Trying to run the same DB and workload on this commit:

https://github.com/qdrant/qdrant/tree/3398ac9848e70d7d72b1c5add5eb7f68cf38ae90

No problem so far.

**Comment by starinacool** [comment] 2023-07-31 14:36
No, this commit also hangs HTTP requests  after some time.

**Comment by starinacool** [comment] 2023-08-02 10:56
@generall This is what happened with number of open files after server stoped responding
![image](https://github.com/qdrant/qdrant/assets/221450/e2aa9289-e41d-45d5-a37a-be53be4386f9)
![image](https://github.com/qdrant/qdrant/assets/221450/c3197959-9870-42a7-b223-54a44d45ba3b)

Then I've stoped the server

**Comment by timvisee** [comment] 2023-08-02 13:12
@starinacool Thank you for providing these graphs, that clearly shows something weird is going on.

I'm currently trying to reproduce this issue, while watching the open file count. So far no luck yet though. Due to the data size this definitely takes some time.

Do you possibly have some additional pointers to help me reproduce this more easily?

**Comment by starinacool** [comment] 2023-08-02 13:37
@timvisee I can provide you with a dataset. It is 46Gb in size.

**Comment by timvisee** [comment] 2023-08-02 15:13
> I can provide you with a dataset. It is 46Gb in size.

Yeah, if you could that would be fantastic.

I did create a similar collection (twice now) with [`bfb`](https://github.com/qdrant/bfb).

```bash
bfb -n 26000000 -d 312 --on-disk-payload --on-disk-hnsw --on-disk-vectors true --quantization scalar --quantization-in-ram false --timeout 30
```

I'm currently running a search/recommend load on it, but I don't see the number of open files growing. It caps at about 200 total.

**Comment by starinacool** [comment] 2023-08-02 16:12
@timvisee

**Comment by timvisee** [comment] 2023-08-02 16:14
Ouch. I forgot that I'm currently on a mobile connection, so I can't easily pull in 46GB. :man_facepalming: 
Thanks a lot for preparing and sharing though.

Someone else on our team may be able to give this a shot instead.

Note that my test setup that is currently running still doesn't show any strange behavior.

**Comment by starinacool** [comment] 2023-08-02 16:14
@timvisee I want to stress that increase in open files happens after server stops responding to HTTP requests.

**Comment by starinacool** [comment] 2023-08-02 16:16
@timvisee If I use only recommend API, or only upserts server works as expected.
The problem arise only when I do both. After several hours.

**Comment by timvisee** [comment] 2023-08-02 16:16
> @timvisee I want to stress that increase in open files happens after server stops responding to HTTP requests.

Good addition! I guessed the HTTP issues were a result of the number of open files, but it is the other way around.

I haven't seen this issue of HTTP locking up before.

**Comment by timvisee** [comment] 2023-08-03 11:37
I'm afraid I cannot reproduce the problem at this time. I've tried various configurations with various loads, and have run it over night. Having 26 million new/old points, with 1k upserted every second and 500 recommendation requests concurrently and the payload filter as you described.

With all of this I was unable to trigger the HTTP getting stuck issue. The number of open files never surpassed 320 and fluctuated a bit, which are normal numbers.

For your information, I ran this on a machine with 24 AMD cores, 32GB RAM, an NVMe drive and Ubuntu 23.04. That makes it somewhat similar to your configuration.

I wonder if we can greatly simplify the testing scenario to make debugging a lot easier.

**Comment by starinacool** [comment] 2023-08-14 13:28
@timvisee , Interesting observation. When I do recommend requests without any additional filters. Using only point id as a recommend parameter. The server stops hanging.

**Comment by agourlay** [comment] 2023-08-22 19:00
It is not clear to me which qdrant version you are using.

Could you please retry your test scenario with the latest release [1.4.1](https://github.com/qdrant/qdrant/releases/tag/v1.4.1) as it contains several bug fixes.

**Comment by generall** [comment] 2023-12-10 16:49
I am assuming this problem was fixed in latest versions, please feel free to re-open if it reproduces again

**Closed by generall** 2023-12-10 16:49 UTC
Labels: bug, can't reproduce

**Comment by QuantumStaticFR** [comment] 2024-08-06 21:12
I am facing the same issue while running qdrant locally.

**Comment by agourlay** [comment] 2024-08-07 08:27
@QuantumStaticFR Yes, please create a new issue with the specifics of your environment :)
